# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0070_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='logo_override',
            field=models.CharField(blank=True, default=b'', max_length=150, verbose_name='Logo Override'),
        ),
    ]
